name: formatting_check
run-name: Check code formatting
on: [push, pull_request]
jobs:
  formatting_check:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo gem install mdl
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install tox
        run: python -m pip install --upgrade pip tox
      - name: Run tox
        run: tox -e format_check
